services:
  scala-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: >
      sh -c "/myapp/dist/bin/back"
    volumes:
      - "./dbschema:/dbschema"
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
      EDGEDB_DSN_BUILD: "toto"
    user: "1000:1000"

