services:
  scala-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: >
      sh -c "edgedb instance link db -H 192.168.1.108 -P 5656 -b main --tls-security insecure -u edgedb -p password --overwrite --non-interactive &&  edgedb migrate -I db && /myapp/dist/bin/back"
    volumes:
      - "./dbschema:/dbschema"
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
    user: "1000:1000"

