name: Test
on:
  push:
    branches: [ 'main', 'dev' ]

jobs:
  test:
    timeout-minutes: 15
    # need to be newer than `ubuntu-20.04` because of scalafmt native binary
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
      - uses: bleep-build/bleep-setup-action@0.0.2
      - uses: edgedb/setup-edgedb@v1
      - uses: coursier/cache-action@v6
      - name: Bleep test
        run: |
          edgedb migrate 
          bleep test