name: Test & Deploy
on:
  push:
    branches: [ 'main', 'dev' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    services:
      edgedb:
        image: edgedb/edgedb:latest
        ports:
          - 5656:5656
        options: >-
          --health-cmd "edgedb-server --version"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      CI: true
      NEXTCLOUD_USERNAME: ${{ secrets.NEXTCLOUD_USERNAME }}
      NEXTCLOUD_PASSWORD: ${{ secrets.NEXTCLOUD_PASSWORD }}
      NEXTCLOUD_URL: ${{ secrets.NEXTCLOUD_URL }}
      AUTH_SECRET_KEY: ${{ secrets.AUTH_SECRET_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Scala
        uses: coursier/setup-action@v1
        with:
          jvm: adopt:17
          apps: bleep, scalafmt

      - name: Setup Bleep
        uses: bleep-build/bleep-setup-action@0.0.2

      - name: Setup Gel
        uses: geldata/setup-gel@v1

      - name: Cache dependencies
        uses: coursier/cache-action@v6

      - name: Run migrations
        run: edgedb migrate

      - name: Run tests
        run: bleep test

      - name: Trigger deployment
        if: success() && github.ref == 'refs/heads/main'
        env:
          COOLIFY_API_TOKEN: ${{ secrets.COOLIFY_API_TOKEN }}
          COOLIFY_API_URL: ${{ secrets.COOLIFY_API_URL }}
        run: |
          curl -X GET "$COOLIFY_API_URL" \
            -H "Authorization: Bearer $COOLIFY_API_TOKEN" \
            -H "Content-Type: application/json" \
            --fail