name: CI Pipeline

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      CI: true
      NEXTCLOUD_USERNAME: ${{ secrets.NEXTCLOUD_USERNAME }}
      NEXTCLOUD_PASSWORD: ${{ secrets.NEXTCLOUD_PASSWORD }}
      NEXTCLOUD_URL: ${{ secrets.NEXTCLOUD_URL }}
      AUTH_SECRET_KEY: ${{ secrets.AUTH_SECRET_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bleep
        uses: bleep-build/bleep-setup-action@0.0.2

      - name: Setup Gel
        uses: geldata/setup-gel@v1

      - name: Setup Coursier cache
        uses: coursier/cache-action@v6

      - name: Cache Ivy2 and SBT
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt', '**/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Run migrations & tests
        run: |
          edgedb migrate
          bleep test

  deploy:
    name: Deploy to Coolify
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && success()
    steps:
      - name: Trigger Coolify Deployment
        run: |
          curl --fail -X GET "${{ secrets.COOLIFY_API_URL }}" \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_API_TOKEN }}" \
            -H "Content-Type: application/json"
