name: Test
on:
  push:
    branches: [ 'main', 'dev' ]

jobs:
  test:
    timeout-minutes: 15
    # need to be newer than `ubuntu-20.04` because of scalafmt native binary
    runs-on: ubuntu-latest
    env:
      CI: true
      NEXTCLOUD_USERNAME: ${{ secrets.NEXTCLOUD_USERNAME }}
      NEXTCLOUD_PASSWORD: ${{ secrets.NEXTCLOUD_PASSWORD }}
      NEXTCLOUD_URL: ${{ secrets.NEXTCLOUD_URL }}
      AUTH_SECRET_KEY: ${{ secrets.AUTH_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: bleep-build/bleep-setup-action@0.0.2
      - uses: geldata/setup-gel@v1
      - uses: coursier/cache-action@v6
      - name: Bleep test
        run: |
          edgedb migrate
          bleep test


      - name: Trigger Coolify Deployment
        if: success()
        run: |
          curl -X GET "${{ secrets.COOLIFY_API_URL }}" \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_API_TOKEN }}" \
            -H "Content-Type: application/json"